import Head from "next/head";
import React from "react";
import Every from "./components/Every/Every";
import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";

const EveryonePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Every />
      <Footer />
    </>
  );
};

export default EveryonePage;
