import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import TaskRate from "../components/Every/TaskRate";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import Slider from "../components/Main/Slider";
import Tab from "../components/Every/Tab";
import Office from "../components/Evaluation/Office";
import Certification from "../components/Every/Certification";

const Slug = () => {
  const router = useRouter();
  const { slug } = router.query;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {slug === "task-rate" ? (
        <TaskRate />
      ) : slug === "report" ? (
        <div className="bg-light">
          <Slider />
          <Tab />
          <Office />
        </div>
      ) : (
        <Certification />
      )}

      <Footer />
    </>
  );
};

export default Slug;
